// This file will be auto-generated by `supabase gen types typescript --local`
// Replace this placeholder with the generated output after running `supabase start` + migrations.
// Run: npx supabase gen types typescript --local > src/types/database.ts
//
// These types are manually maintained until the local Supabase instance is available.
// Derived from supabase/migrations/001_initial_schema.sql

export type Database = {
  public: {
    Tables: {
      stores: {
        Row: {
          id: string
          name: string
          owner_auth_id: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          owner_auth_id: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          owner_auth_id?: string
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
      staff: {
        Row: {
          id: string
          store_id: string
          auth_user_id: string | null
          name: string
          pin_hash: string | null
          role: 'owner' | 'staff'
          is_active: boolean
          pin_attempts: number
          pin_locked_until: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          store_id: string
          auth_user_id?: string | null
          name: string
          pin_hash?: string | null
          role: 'owner' | 'staff'
          is_active?: boolean
          pin_attempts?: number
          pin_locked_until?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          store_id?: string
          auth_user_id?: string | null
          name?: string
          pin_hash?: string | null
          role?: 'owner' | 'staff'
          is_active?: boolean
          pin_attempts?: number
          pin_locked_until?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'staff_store_id_fkey'
            columns: ['store_id']
            isOneToOne: false
            referencedRelation: 'stores'
            referencedColumns: ['id']
          }
        ]
      }
      categories: {
        Row: {
          id: string
          store_id: string
          name: string
          sort_order: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          store_id: string
          name: string
          sort_order?: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          store_id?: string
          name?: string
          sort_order?: number
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'categories_store_id_fkey'
            columns: ['store_id']
            isOneToOne: false
            referencedRelation: 'stores'
            referencedColumns: ['id']
          }
        ]
      }
      products: {
        Row: {
          id: string
          store_id: string
          category_id: string | null
          name: string
          sku: string | null
          barcode: string | null
          price_cents: number
          stock_quantity: number
          reorder_threshold: number
          image_url: string | null
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          store_id: string
          category_id?: string | null
          name: string
          sku?: string | null
          barcode?: string | null
          price_cents: number
          stock_quantity?: number
          reorder_threshold?: number
          image_url?: string | null
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          store_id?: string
          category_id?: string | null
          name?: string
          sku?: string | null
          barcode?: string | null
          price_cents?: number
          stock_quantity?: number
          reorder_threshold?: number
          image_url?: string | null
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'products_store_id_fkey'
            columns: ['store_id']
            isOneToOne: false
            referencedRelation: 'stores'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'products_category_id_fkey'
            columns: ['category_id']
            isOneToOne: false
            referencedRelation: 'categories'
            referencedColumns: ['id']
          }
        ]
      }
      orders: {
        Row: {
          id: string
          store_id: string
          staff_id: string | null
          channel: 'pos' | 'online'
          status: 'pending' | 'completed' | 'refunded' | 'expired' | 'pending_pickup' | 'ready' | 'collected'
          subtotal_cents: number
          gst_cents: number
          total_cents: number
          discount_cents: number
          payment_method: 'eftpos' | 'cash' | 'stripe' | null
          stripe_session_id: string | null
          stripe_payment_intent_id: string | null
          customer_email: string | null
          notes: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          store_id: string
          staff_id?: string | null
          channel: 'pos' | 'online'
          status: 'pending' | 'completed' | 'refunded' | 'expired' | 'pending_pickup' | 'ready' | 'collected'
          subtotal_cents: number
          gst_cents: number
          total_cents: number
          discount_cents?: number
          payment_method?: 'eftpos' | 'cash' | 'stripe' | null
          stripe_session_id?: string | null
          stripe_payment_intent_id?: string | null
          customer_email?: string | null
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          store_id?: string
          staff_id?: string | null
          channel?: 'pos' | 'online'
          status?: 'pending' | 'completed' | 'refunded' | 'expired' | 'pending_pickup' | 'ready' | 'collected'
          subtotal_cents?: number
          gst_cents?: number
          total_cents?: number
          discount_cents?: number
          payment_method?: 'eftpos' | 'cash' | 'stripe' | null
          stripe_session_id?: string | null
          stripe_payment_intent_id?: string | null
          customer_email?: string | null
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'orders_store_id_fkey'
            columns: ['store_id']
            isOneToOne: false
            referencedRelation: 'stores'
            referencedColumns: ['id']
          }
        ]
      }
      order_items: {
        Row: {
          id: string
          order_id: string
          product_id: string
          product_name: string
          product_sku: string | null
          quantity: number
          unit_price_cents: number
          discount_cents: number
          line_total_cents: number
          gst_cents: number
          created_at: string
        }
        Insert: {
          id?: string
          order_id: string
          product_id: string
          product_name: string
          product_sku?: string | null
          quantity: number
          unit_price_cents: number
          discount_cents?: number
          line_total_cents: number
          gst_cents: number
          created_at?: string
        }
        Update: {
          id?: string
          order_id?: string
          product_id?: string
          product_name?: string
          product_sku?: string | null
          quantity?: number
          unit_price_cents?: number
          discount_cents?: number
          line_total_cents?: number
          gst_cents?: number
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'order_items_order_id_fkey'
            columns: ['order_id']
            isOneToOne: false
            referencedRelation: 'orders'
            referencedColumns: ['id']
          }
        ]
      }
      promo_codes: {
        Row: {
          id: string
          store_id: string
          code: string
          discount_type: 'percentage' | 'fixed'
          discount_value: number
          min_order_cents: number
          max_uses: number | null
          current_uses: number
          expires_at: string | null
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          store_id: string
          code: string
          discount_type: 'percentage' | 'fixed'
          discount_value: number
          min_order_cents?: number
          max_uses?: number | null
          current_uses?: number
          expires_at?: string | null
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          store_id?: string
          code?: string
          discount_type?: 'percentage' | 'fixed'
          discount_value?: number
          min_order_cents?: number
          max_uses?: number | null
          current_uses?: number
          expires_at?: string | null
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'promo_codes_store_id_fkey'
            columns: ['store_id']
            isOneToOne: false
            referencedRelation: 'stores'
            referencedColumns: ['id']
          }
        ]
      }
      stripe_events: {
        Row: {
          id: string
          stripe_event_id: string
          type: string
          processed: boolean
          created_at: string
        }
        Insert: {
          id?: string
          stripe_event_id: string
          type: string
          processed?: boolean
          created_at?: string
        }
        Update: {
          id?: string
          stripe_event_id?: string
          type?: string
          processed?: boolean
          created_at?: string
        }
        Relationships: []
      }
      cash_sessions: {
        Row: {
          id: string
          store_id: string
          staff_id: string
          opened_at: string
          closed_at: string | null
          opening_float_cents: number
          closing_float_cents: number | null
          expected_cash_cents: number | null
          actual_cash_cents: number | null
          variance_cents: number | null
          notes: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          store_id: string
          staff_id: string
          opened_at?: string
          closed_at?: string | null
          opening_float_cents: number
          closing_float_cents?: number | null
          expected_cash_cents?: number | null
          actual_cash_cents?: number | null
          variance_cents?: number | null
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          store_id?: string
          staff_id?: string
          opened_at?: string
          closed_at?: string | null
          opening_float_cents?: number
          closing_float_cents?: number | null
          expected_cash_cents?: number | null
          actual_cash_cents?: number | null
          variance_cents?: number | null
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'cash_sessions_store_id_fkey'
            columns: ['store_id']
            isOneToOne: false
            referencedRelation: 'stores'
            referencedColumns: ['id']
          }
        ]
      }
    }
    Views: Record<string, never>
    Functions: Record<string, never>
  }
}
