// This file will be auto-generated by `supabase gen types typescript --local`
// Replace this placeholder with the generated output after running `supabase start` + migrations.
// Run: npx supabase gen types typescript --local > src/types/database.ts

export type Database = {
  public: {
    Tables: {
      stores: { Row: Record<string, unknown>; Insert: Record<string, unknown>; Update: Record<string, unknown> }
      staff: { Row: Record<string, unknown>; Insert: Record<string, unknown>; Update: Record<string, unknown> }
      categories: { Row: Record<string, unknown>; Insert: Record<string, unknown>; Update: Record<string, unknown> }
      products: { Row: Record<string, unknown>; Insert: Record<string, unknown>; Update: Record<string, unknown> }
      orders: { Row: Record<string, unknown>; Insert: Record<string, unknown>; Update: Record<string, unknown> }
      order_items: { Row: Record<string, unknown>; Insert: Record<string, unknown>; Update: Record<string, unknown> }
      promo_codes: { Row: Record<string, unknown>; Insert: Record<string, unknown>; Update: Record<string, unknown> }
      stripe_events: { Row: Record<string, unknown>; Insert: Record<string, unknown>; Update: Record<string, unknown> }
      cash_sessions: { Row: Record<string, unknown>; Insert: Record<string, unknown>; Update: Record<string, unknown> }
    }
  }
}
